from .styles import Styles
from .auth_view import AuthView
from .dashboard_view import DashboardView
from .upload_view import UploadView
from .ocr_view import OCRView
from .analysis_view import AnalysisView
from .history_view import HistoryView
from .settings_view import SettingsView
from .main_window import MainWindow
